from motor.importacao import importar_csv_largo

df = importar_csv_largo(r"D:\Raspagem de Dados jogo do bicho\dados\jogo_do_bicho_2024.csv")

print("=" * 60)
print("IMPORTAÇÃO — RESUMO")
print("=" * 60)
print(f"Linhas importadas: {len(df)}")
print(f"Colunas: {list(df.columns)}")
print()
print("Primeiras 10 linhas:")
print(df.head(10).to_string(index=False))
print()
print("Últimas 5 linhas:")
print(df.tail(5).to_string(index=False))
print()
print("Modalidades encontradas:")
print(df["modalidade"].value_counts().to_string())
print()
print("Datas: de", df["data"].min(), "até", df["data"].max())
print()
print("Milhares com menos de 4 dígitos:", (df["milhar"].str.len() != 4).sum())
print("Milhares vazios:", (df["milhar"] == "").sum())
print()
print("Prêmios distintos:", sorted(df["premio"].unique()))
